<?php

namespace Database\Seeders;

use App\Models\Criterion;
use App\Models\CriterionEvaluation;
use App\Models\CriterionYear;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CriterionSeeder extends Seeder
{
    public function run(): void
    {
        $criteria = [
            [
                'main' => [
                    'name' => [
                        'uz' => 'O‘quv-uslubiy ishlar va o‘qitish sifati',
                        'kaa' => 'Oqíw-metodikalíq jumíslar hám oqítíw sapasí',
                        'ru' => 'Учебно-методическая работа и качество обучения',
                        'en' => 'Educational and methodological work and teaching quality',
                    ],
                    'report_id' => 1, 'upload' => '1', 'status' => '1',
                ],
                'children' => [
                    [
                        'name' => [
                            'uz' => 'Sifatli o‘quv kontentlari (videodarslar, videoroliklar, taqdimotlar)',
                            'kaa' => 'Sapalı oqıw kontentleri (videosabaqlar, videorolikler, prezentaciyalar)',
                            'ru' => 'Качественный образовательный контент (видеоуроки, видеоролики, презентации)',
                            'en' => 'High-quality educational content (video lessons, videos, presentations)',
                        ],
                        'desc' => [
                            'uz' => 'O‘quv kontentlari “YouTube” havola kiritiladi. <br>Videodarslar-1,5 ball, videoroliklar-1 ball, taqdimotlar-0,5 ball.',
                            'kaa' => 'Oqıw kontentleri "YouTube" siltemesi qosıladı. <br>Videosabaqlar-1,5 ball, videorolikler-1 ball, prezentaciyalar-0,5 ball.',
                            'ru' => 'Учебный контент Введите ссылку на "YouTube." <br>Видеоуроки - 1,5 балла, видеоролики - 1 балл, презентации - 0,5 балла.',
                            'en' => 'Educational content will be linked to "YouTube." <br>Video lessons - 1.5 points, video clips - 1 point, presentations - 0.5 points.',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'foreign_lang' => 4,
                            'hold_degrees' => 3,
                            'no_degrees' => 6,
                            'physical' => 4,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => "You are an AI evaluator. Review the submitted YouTube links and descriptions. Determine the content type and assign points: 'videodars' (video lesson) = 1.5 points, 'videorolik' (video clip) = 1 point, 'taqdimot' (presentation) = 0.5 points. Ensure the links are valid. Return a JSON object strictly in this format: {\"status\": true/false, \"score\": calculated_total_score, \"reason\": \"explanation\"}."
                    ],
                    [
                        'name' => [
                            'uz' => 'Nashr etilgan darslik',
                            'kaa' => 'Basıp shıǵarılǵan sabaqlíq',
                            'ru' => 'Опубликованный учебник',
                            'en' => 'Published textbook',
                        ],
                        'desc' => [
                            'uz' => 'Belgilangan tartib va talablar asosida tayyorlanib, chop qilinganligi hamda ushbu darslik bo‘yicha vazirlik yoki universitetning o‘quv adabiyotlariga nashr ruxsatnomasi, ISBN raqami asosida aniqlanadi. Mualliflik ulushi inobatga olinadi. Baholash usuli: har bir bosma tabog‘i uchun 0,4 ball.',
                            'kaa' => 'Belgilengen tártip hám talaplar tiykarında tayarlanıp, basıp shıǵarılǵanlıǵı hám de usı sabaqlıq boyınsha ministrlik yamasa universitettiń oqıw ádebiyatlarına baspa ruxsatnaması, ISBN nomeri tiykarında anıqlanadı. Avtorlıq úlesi esapqa alınadı. Bahalaw usili: hár bir baspa tabaq ushin 0,4 ball.',
                            'ru' => 'Подготовка и издание учебника в соответствии с установленным порядком и требованиями определяется на основании разрешения министерства или университета на публикацию учебной литературы по данному учебнику, номера ISBN. Авторский вклад учитывается. Метод оценки: 0,4 балла за каждый печатный лист.',
                            'en' => 'The preparation and publication of the textbook in accordance with the established procedure and requirements, as well as the publication permit for educational literature from the ministry or university, are determined based on the ISBN number. The author’s contribution is taken into account. Assessment method: 0.4 points for each printed sheet.',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'manual',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 6,
                            'no_degrees' => 5,
                            'foreign_lang' => 5,
                            'physical' => 5,
                        ],
                        'year' => 2025,
                        'formula_id' => 2,
                        'ai_prompt' => null,
                    ],
                    [
                        'name' => [
                            'uz' => 'Nashr etilgan o‘quv qo‘llanma',
                            'kaa' => 'Basıp shıǵarılǵan oqıw qollanba',
                            'ru' => 'Изданное учебное пособие',
                            'en' => 'Published study guide',
                        ],
                        'desc' => [
                            'uz' => 'Belgilangan tartib va talablar asosida tayyorlanib, chop qilinganligi hamda ushbu o‘quv qo‘llanma bo‘yicha vazirlik yoki universitetning o‘quv adabiyotlariga nashr ruxsatnomasi, ISBN raqami asosida aniqlanadi. Mualliflik ulushi inobatga olinadi. Baholash usuli: har bir bosma tabog‘i uchun 0,3 ball.',
                            'kaa' => 'Belgilengen tártip hám talaplar tiykarında tayarlanıp, basıp shıǵarılǵanlıǵı hám de usı oqıw qollanba boyınsha ministrlik yamasa universitettiń oqıw ádebiyatlarına baspa ruxsatnaması, ISBN nomeri tiykarında anıqlanadı. Avtorlıq úlesi esapqa alınadı. Bahalaw usili: hár bir baspa tabaq ushın 0,3 ball.',
                            'ru' => 'Подготовка и публикация в соответствии с установленным порядком и требованиями, а также разрешение министерства или университета на публикацию учебной литературы по данному учебному пособию определяются на основании номера ISBN. Авторский вклад учитывается. Метод оценки: 0,3 балла за каждый печатный лист.',
                            'en' => 'Preparation and publication in accordance with the established procedure and requirements, as well as the publication permit of the ministry or university for educational literature under this textbook, are determined based on the ISBN number. The author’s contribution is taken into account. Assessment method: 0.3 points for each printed sheet.',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'manual',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 5,
                            'no_degrees' => 4,
                            'foreign_lang' => 4,
                            'physical' => 4,
                        ],
                        'year' => 2025,
                        'formula_id' => 2,
                        'ai_prompt' => null,
                    ],
                    [
                        'name' => [
                            'uz' => 'Elektron darslik va o‘quv qo‘llanma yaratish yoki boshqa tillarda tarjima qilganligi',
                            'kaa' => 'Elektron sabaqlıq hám oqıw qollanbasın jaratıw yamasa basqa tillerge awdarǵanlıǵı',
                            'ru' => 'Создание электронных учебников и учебных пособий или их перевод на другие языки',
                            'en' => 'Creating electronic textbooks and teaching aids or translating them into other languages',
                        ],
                        'desc' => [
                            'uz' => 'Belgilangan tartib va talablar asosida elektron darslik va o‘quv qo‘llanma yaratilganligi yoki boshqa tillarda tarjima qilinganligi  tayyorlanib chop qilinganligi hamda ushbu o‘quv adabiyoti  bo‘yicha universitetning nashr ruxsatnomasi, ISBN raqami asosida aniqlanadi. Mualliflik ulushi inobatga olinadi.',
                            'kaa' => 'Belgilengen tártip hám talaplar tiykarında elektron sabaqlıq hám oqıw qollanba jaratılǵanlıǵı yamasa basqa tillerge awdarılǵanlıǵı tayarlanıp basıp shıǵarılǵanlıǵı hám de usı oqıw ádebiyatı boyınsha universitettiń baspa ruxsatnaması, ISBN nomeri tiykarında anıqlanadı. Avtorlıq úlesi esapqa alınadı.',
                            'ru' => 'Создание электронного учебника и учебного пособия на основе установленного порядка и требований или их перевод на другие языки, подготовка и издание, а также разрешение университета на публикацию данной учебной литературы определяются на основании номера ISBN. Авторский вклад учитывается.',
                            'en' => 'Based on the established procedure and requirements, the creation of electronic textbooks and teaching aids or their translation into other languages, as well as the preparation and publication of this educational literature, is determined on the basis of the university’s publication permit and ISBN number. The author’s contribution is taken into account.',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 5,
                            'no_degrees' => 4,
                            'foreign_lang' => 4,
                            'physical' => 4,
                        ],
                        'year' => 2025,
                        'formula_id' => 2,
                        'ai_prompt' => "You are an AI evaluator. Read the provided document details. Verify if it is an electronic textbook, manual, or a translation. Look for the presence of an ISBN number and a university publication permit. Return a JSON object strictly in this format: {\"status\": true/false, \"author_share\": number_if_mentioned_or_1, \"reason\": \"explanation of found ISBN and permits\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => 'Ta’lim yo‘nalishlari va mutaxassisliklari bo‘yicha Fan (ishchi) dasturi va sillabus tayyorlash',
                            'kaa' => 'Bilimlendiriw baǵdarları hám qánigelikleri boyınsha Pán (jumısshı) baǵdarlaması hám sillabus tayarlaw',
                            'ru' => 'Подготовка предметной (рабочей) программы и силлабуса по направлениям и специальностям образования',
                            'en' => 'Preparation of the subject (working) program and syllabus for educational fields and specialties',
                        ],
                        'desc' => [
                            'uz' => 'Belgilangan tartib va talablar asosida tayyorlanib tasdiqlangan ta’lim yo‘nalishlari va mutaxassisliklari bo‘yicha Fan (ishchi) dasturi va sillabus tayyorlaganligi asosida aniqlanadi.',
                            'kaa' => 'Belgilengen tártip hám talaplar tiykarında tayarlanıp tastıyıqlanǵan tálim baǵdarları hám qánigelikleri boyınsha Pán (jumısshı) baǵdarlaması hám sillabus tayarlanǵanlıǵı tiykarında anıqlanadı.',
                            'ru' => 'Определяется на основе подготовки предметной (рабочей) программы и силлабуса по направлениям и специальностям образования, подготовленным и утвержденным в установленном порядке и требованиях.',
                            'en' => 'It is determined based on the preparation of a subject (working) program and syllabus for educational fields and specialties prepared and approved in accordance with the established procedure and requirements.',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'department',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 3,
                            'no_degrees' => 3,
                            'foreign_lang' => 3,
                            'physical' => 3,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => null,
                    ],
                    [
                        'name' => [
                            'uz' => 'Talabalarning davomati va o‘zlashtirish ko‘rsatkichlari',
                            'kaa' => 'Studentlerdiń qatnasıwı hám ózlestiriw kórsetkishleri',
                            'ru' => 'Посещаемость и показатели успеваемости студентов',
                            'en' => 'Student attendance and academic performance',
                        ],
                        'desc' => [
                            'uz' => 'hemis.karsu.uz:<br>a) Hemisdan foydalanish bo‘yicha talabalar davomati<br>b) talabalar o‘zlashtirish ko‘rsatkichi',
                            'kaa' => 'hemis.karsu.uz:<br>a) Hemisden paydalanıw boyınsha studentler qatnasıwı<br>b) studentler ózlestiriw kórsetkishi',
                            'ru' => 'hemis.karsu.uz:<br>а) посещаемость студентов по использованию hemis<br>б) показатель успеваемости студентов',
                            'en' => 'hemis.karsu.uz:<br>a) Student attendance for using Hemis<br>b) student performance indicator',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'hemis_integrate',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 8,
                            'no_degrees' => 8,
                            'foreign_lang' => 8,
                            'physical' => 8,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => null,
                    ],
                    [
                        'name' => [
                            'uz' => 'O‘qitish sifati darajasi',
                            'kaa' => 'Oqıtıw sapası dárejesi',
                            'ru' => 'Уровень качества образования',
                            'en' => 'Teaching quality level',
                        ],
                        'desc' => [
                            'uz' => 'Semestr yakuni bo‘yicha o‘tkaziladigan talabalar o‘rtasidagi anonim (ijtimoiy) so‘rovnoma natijalariga ko‘ra aniqlanadi',
                            'kaa' => 'Semestr juwmaǵı boyınsha ótkeriletuǵın studentler arasında anonim (sociallıq) sorawnama nátiyjelerine bola anıqlanadı.',
                            'ru' => 'Определяется по результатам анонимного (социального) опроса среди студентов, проводимого по итогам семестра.',
                            'en' => 'It is determined based on the results of an anonymous (social) survey conducted among students at the end of the semester.',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'vote_integrate',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 2,
                            'no_degrees' => 2,
                            'foreign_lang' => 2,
                            'physical' => 2,
                        ],
                        'year' => 2025,
                        'formula_id' => 2,
                        'ai_prompt' => null,
                    ],
                    [
                        'name' => [
                            'uz' => 'Mavjud va yangi laboratoriya ishini tayyorlash va joriy etish, shuningdek virtual laboratoriya ishini tayyorlash va joriy etish lobarotoriya va amaliy mashg‘ulotlar uchun uslubiy ko‘rsatmalar',
                            'kaa' => 'Bar hám jańa laboratoriyalıq jumıstı tayarlaw hám engiziw, sonday-aq, virtual laboratoriyalıq jumıstı tayarlaw hám engiziw laboratoriyalıq hám ámeliy shınıǵıwlar ushın metodikalıq kórsetpeler.',
                            'ru' => 'Подготовка и внедрение существующей и новой лабораторной работы, а также подготовка и внедрение виртуальной лабораторной работы методические указания для лабораторных и практических занятий',
                            'en' => 'Methodological guidelines for laboratory and practical sessions for the preparation and implementation of existing and new laboratory work, as well as the preparation and implementation of virtual laboratory work',
                        ],
                        'desc' => [
                            'uz' => 'Yangi laboratoriya va virtual laboratoriya-1 ball<br>Laboratoriya va amaliy mashg‘ulotlar uchun uslubiy qo‘llanma-1 ball',
                            'kaa' => 'Jańa laboratoriya hám virtual laboratoriya-1 ball<br>Laboratoriya hám ámeliy sabaqlar ushın metodikalıq qollanba-1 ball',
                            'ru' => 'Новая лаборатория и виртуальная лаборатория-1 балл<br>Методическое пособие для лабораторных и практических занятий-1 балл',
                            'en' => 'New laboratory and virtual laboratory - 1 point<br>Methodological guide for laboratory and practical sessions - 1 point',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 2,
                            'no_degrees' => 2,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => "You are an AI evaluator. Check the evidence to see if the professor created a new/virtual laboratory work (worth 1 point) or a methodological guide for laboratory/practical classes (worth 1 point). Return a JSON object strictly in this format: {\"status\": true/false, \"score\": total_points_up_to_2, \"reason\": \"explanation of what was created\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => 'Professor-o‘qituvchining bakalavriat ta’lim yo‘nalishlariga abituriyent-larni (qabul komissiyasiga) jalb etishda targ‘ibot va tashviqot jarayonlarida faol ishtirok etganligi jalb etilishi hamda bakalavr va magistrlarining bandligi va ishga joylashtirilishida ishtiroki',
                            'kaa' => 'Professor-oqıtıwshınıń bakalavriat tálim baǵdarlarına abiturientlerdi (qabıllaw komissiyasına) tartıwda úgit-násiyatlaw hám úgit-násiyatlaw processlerinde belsene qatnasqanlıǵı jáne bakalavr hám magistrlerdiń bántligi hám jumısqa jaylastırılıwında qatnasqanlıǵı;',
                            'ru' => 'Активное участие профессора-преподавателя в процессах пропаганды и агитации при привлечении абитуриентов (в приемную комиссию) на направления образования бакалавриата, а также участие в трудоустройстве и трудоустройстве бакалавров и магистров',
                            'en' => 'Active participation of the professor-teacher in the advocacy and propaganda processes for attracting applicants (to the admissions committee) to undergraduate educational programs, as well as their involvement in the employment and placement of bachelors and masters',
                        ],
                        'desc' => [
                            'uz' => 'Bakalavriat ta’lim yo‘nalishlariga abituriyentlarni qabul jarayoniga jalb etish - 1 ball<br>Bakalavriat talabalarining bandligi va ishga joylashtirishdagi ishtiroki - 1 ball<br>Magistrantlarning bandligi va ishga joylashtirishdagi ishtiroki - 1 ball',
                            'kaa' => 'Bakalavriat tálim baǵdarlarına abiturientlerdi qabıllaw procesine tartıw - 1 ball<br>Bakalavriat studentleriniń bántligi hám jumısqa jaylastırıwda qatnasıwı - 1 ball<br>Magistrantlardıń bántligi hám jumısqa jaylastırıwda qatnasıwı - 1 ball',
                            'ru' => 'Вовлечение абитуриентов в процесс приема на направления образования бакалавриата - 1 балл<br>Участие студентов бакалавриата в трудоустройстве и трудоустройстве - 1 балл<br>Участие магистрантов в трудоустройстве и трудоустройстве - 1 балл',
                            'en' => 'Involvement of applicants in the admission process for undergraduate programs - 1 point<br>Participation of undergraduate students in employment and placement - 1 point<br>Participation of master’s students in employment and placement - 1 point',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 3,
                            'no_degrees' => 3,
                            'foreign_lang' => 3,
                            'physical' => 3,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => "You are an AI evaluator. Review the submitted evidence. Check for the professor's involvement in: 1) attracting applicants to bachelor programs (1 pt), 2) employment of bachelors (1 pt), 3) employment of masters (1 pt). Return a JSON object strictly in this format: {\"status\": true/false, \"score\": total_points_up_to_3, \"reason\": \"explanation of which criteria were met\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => 'Professional ta’lim, akademik litsey, kasb-hunar va o‘rta ta’lim maktablarida Master-klass darslarini o‘tish',
                            'kaa' => 'Professional bilimlendiriw, akademiyalıq licey, kásip-óner hám orta bilim beriw mekteplerinde Master-klass sabaqların ótkeriw',
                            'ru' => 'Проведение мастер-классов в профессиональных образовательных учреждениях, академических лицеях, профессиональных и средних образовательных школах',
                            'en' => 'Conducting master classes in vocational schools, academic lyceums, vocational and secondary educational institutions',
                        ],
                        'desc' => [
                            'uz' => 'Belgilangan tartib va talablar asosida o‘tkazilgan, rejalashtirilgan, tasdiqlovchi hujjatlar, dars tahlillari, videofayllar orqali aniqlanadi',
                            'kaa' => 'Belgilengen tártip hám talaplar tiykarında ótkerilgen, rejelestirilgen, tastıyıqlawshı hújjetler, sabaq tallawları, video fayllar arqalı anıqlanadı.',
                            'ru' => 'Определяется посредством плановых, подтверждающих документов, анализа уроков и видеофайлов, проведенных в соответствии с установленным порядком и требованиями.',
                            'en' => 'It is determined through planned, supporting documents, lesson analyses, and video files conducted in accordance with established procedures and requirements.',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 2,
                            'no_degrees' => 2,
                            'foreign_lang' => 3,
                            'physical' => 3,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => "You are an AI evaluator. Review the provided documents, lesson analyses, or video descriptions. Confirm if the professor conducted a master class at a professional education institution, academic lyceum, or school. Return a JSON object strictly in this format: {\"status\": true/false, \"reason\": \"explanation of evidence found\"}."
                    ],
                ],
            ],
            [
                'main' => [
                    'name' => [
                        'uz' => 'Xalqaro faoliyat hamda qayta tayyorlash va malaka oshirish va xalqaro darajadagi sertifikatlar',
                        'kaa' => 'Xalíq aralíq jumís hám qayta tayarlaw hám qánigelikti arttíríw hám xalíq aralíq dárejedegi sertifikatlar',
                        'ru' => 'Международная деятельность, переподготовка и повышение квалификации, а также сертификаты международного уровня',
                        'en' => 'International activities, retraining and professional development, and international certificates',
                    ],
                    'report_id' => 1, 'upload' => '1', 'status' => '1',
                ],
                'children' => [
                    [
                        'name' => [
                            'uz' => 'Sohalar bo‘yicha to‘garaklar, xorijiy tilarni o‘rgatish kurslarni tashkil etish',
                            'kaa' => 'Tarawlar boyınsha dógerekler, shet tillerin úyretiw kursların shólkemlestiriw',
                            'ru' => 'Организация кружков по отраслям, курсов по обучению иностранным языкам',
                            'en' => 'Organization of specialized clubs and foreign language courses',
                        ],
                        'desc' => [
                            'uz' => 'To‘garak va kurslarni tashkil qilganligi to‘g‘risida buyruq, to‘garak va kurs rejasi',
                            'kaa' => 'Dógerek hám kurslardı shólkemlestirgenligi haqqında buyrıq, dógerek hám kurs rejesi.',
                            'ru' => 'Приказ об организации кружков и курсов, план кружка и курса',
                            'en' => 'Order on the organization of clubs and courses, club and course plan',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 1,
                            'no_degrees' => 2,
                            'foreign_lang' => 2,
                            'physical' => 2,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => "You are an AI evaluator. Review the document. Look for an official order (buyruq) and a working plan (reja) proving the organization of a specialized club or a foreign language teaching course. Return a JSON object strictly in this format: {\"status\": true/false, \"reason\": \"explanation\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => 'Xorijiy tillarda o‘qitiladigan o‘quv kurslarini olib borish',
                            'kaa' => 'Shet tillerinde oqıtılatuǵın oqıw kursların alıp barıw',
                            'ru' => 'Проведение учебных курсов по иностранным языкам',
                            'en' => 'Conducting training courses in foreign languages',
                        ],
                        'desc' => [
                            'uz' => 'Chet tillari fakulteti tarkibidagi kafedralar bundan mustasno',
                            'kaa' => 'Shet tilleri fakulteti quramındaǵı kafedralar buǵan kirmeydi.',
                            'ru' => 'Исключение составляют кафедры факультета иностранных языков',
                            'en' => 'Except for departments within the Faculty of Foreign Languages',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 2,
                            'no_degrees' => 2,
                            'physical' => 2,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => "You are an AI evaluator. Verify if the evidence shows the professor teaches their academic course in a foreign language. Note: This does not apply if they are from the Faculty of Foreign Languages. Return a JSON object strictly in this format: {\"status\": true/false, \"reason\": \"explanation\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => 'Xorijiy tillarni bilish darajasi',
                            'kaa' => 'Shet tillerin biliw dárejesi',
                            'ru' => 'Уровень владения иностранными языками',
                            'en' => 'Proficiency in foreign languages',
                        ],
                        'desc' => [
                            'uz' => 'Sertifikatlar (A1-A2 - 0,5 ball, B1 - 0,75 ball, B2 - 1 ball, C1 - 1,5 ball, C2 - 2 ball)',
                            'kaa' => 'Sertifikatlar (A1-A2 - 0,5 ball, B1 - 0,75 ball, B2 - 1 ball, C1 - 1,5 ball, C2 - 2 ball)',
                            'ru' => 'Сертификаты (A1-A2 - 0,5 балла, B1 - 0,75 балла, B2 - 1 балл, C1 - 1,5 балла, C2 - 2 балла)',
                            'en' => 'Certificates (A1-A2 - 0.5 points, B1 - 0.75 points, B2 - 1 point, C1 - 1.5 points, C2 - 2 points)',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'manual',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 2,
                            'no_degrees' => 3,
                            'foreign_lang' => 6,
                            'physical' => 3,
                        ],
                        'year' => 2025,
                        'formula_id' => 2,
                        'ai_prompt' => null,
                    ],
                    [
                        'name' => [
                            'uz' => 'Xalqaro loyihalarda ishtiroki',
                            'kaa' => 'Xalıqaralıq joybarlarda qatnasıwı',
                            'ru' => 'Участие в международных проектах',
                            'en' => 'Participation in international projects',
                        ],
                        'desc' => [
                            'uz' => 'Universitet rektori buyrug‘i asosida',
                            'kaa' => 'Universitet rektorı buyrıǵı tiykarında',
                            'ru' => 'На основании приказа ректора университета',
                            'en' => 'Based on the order of the university rector',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'manual',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'foreign_lang' => 4,
                            'physical' => 4,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => null,
                    ],
                    [
                        'name' => [
                            'uz' => 'Pedagog xodimlarning (xorijda (onlayn, offlayn)) qayta tayyorlash, malaka oshirish va stajirovka kurslaridan o‘tganligi hamda almashinuv dasturlarida ishtirok etganligi',
                            'kaa' => 'Pedagog xızmetkerlerdiń (sırt elde (onlayn, offlayn)) qayta tayarlaw, tájiriybe arttırıw hám stajirovka kurslarınan ótkenligi hám de almasıw baǵdarlamalarında qatnasqanlıǵı;',
                            'ru' => 'Прохождение педагогическими работниками курсов переподготовки, повышения квалификации и стажировки (за рубежом (онлайн, оффлайн)) и участие в программах обмена',
                            'en' => 'The completion of retraining, professional development, and internship courses by teaching staff (abroad (online, offline)) and their participation in exchange programs',
                        ],
                        'desc' => [
                            'uz' => 'QS, THE va ARWU kabi xalqaro tashkilotlari reyting ro‘yxatining nufuzli reytingiga kiruvchi ta’lim muassasalarida malaka oshirish va stajirovka kurslaridan o‘tganligi hamda almashinuv dasturlarida ishtirok etganligi (Top-100 bo‘lsa -2 ball, Top-300 bo‘lsa -1.5 , Top-500 bo‘lsa -1 ball, Top-1000 bo‘lsa 0,5 ball)',
                            'kaa' => 'QS, THE hám ARWU sıyaqlı xalıqaralıq shólkemlerdiń reyting diziminiń abıraylı reytingine kiretuǵın bilimlendiriw mákemelerinde qánigelik arttırıw hám stajirovka kurslarınan ótkenligi hám de almasıw baǵdarlamalarında qatnasqanlıǵı (Top-100 bolsa -2 ball, Top-300 bolsa -1.5 , Top-500 bolsa -1 ball, Top-1000 bolsa 0,5 ball)',
                            'ru' => 'Прохождение курсов повышения квалификации и стажировки в образовательных учреждениях, входящих в престижные рейтинги международных организаций, таких как QS, THE и ARWU, а также участие в программах обмена (топ-100 - 2 балла, топ-300 - 1,5 балла, топ-500 - 1 балл, топ-1000 - 0,5 балла)',
                            'en' => 'Completion of advanced training and internship courses at educational institutions included in the prestigious rankings of international organizations such as QS, THE, and ARWU, as well as participation in exchange programs (Top-100 - 2 points, Top-300 - 1.5 points, Top-500 - 1 point, Top-1000 - 0.5 points).',
                        ],
                        'observation' => 'last3years',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 2,
                            'no_degrees' => 3,
                            'foreign_lang' => 2,
                            'physical' => 3,
                        ],
                        'year' => 2025,
                        'formula_id' => 2,
                        'ai_prompt' => "You are an AI evaluator. Review the certificate/document. Identify the foreign host institution and estimate its QS, THE, or ARWU ranking tier. Assign points: Top-100 = 2 pts, Top-300 = 1.5 pts, Top-500 = 1 pt, Top-1000 = 0.5 pts. Return a JSON object strictly in this format: {\"status\": true/false, \"score\": calculated_points, \"reason\": \"explanation of institution and rank\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => 'Professor-o‘qituvchilarni xorijiy ((QS, THE, ARWU TOP-1000 talik) OTMlarida dars mashg‘ulotlarini olib borganligi hamda professor-o‘qituvchilari tomonidan xorijlik olimlar (yekspert, mutaxassis)ni universitetda dars mashg‘ulotlarini olib borishga jalb qilganligi yoki universitetga xorijlik talabalarni jalb qilganligi va universitet bilan halqaro aloqalarni mustahkamlashda qo‘shgan xissasi',
                            'kaa' => 'Professor-oqıtıwshılardıń sırt el (QS, THE, ARWU TOP-1000 lıq) JOOlarında sabaq ótkenligi hám de professor-oqıtıwshıları tárepinen sırt elli ilimpazlardı (ekspert, qánige) universitette sabaq ótiwge tartqanlıǵı yamasa universitetke sırt elli studentlerdi tartqanlıǵı hám de universitet penen xalıqaralıq baylanıslardı bekkemlewde qosqan úlesi;',
                            'ru' => 'Вклад профессоров и преподавателей в проведение занятий в зарубежных вузах (входящих в ТОП-1000 QS, THE, ARWU), а также привлечение профессорами и преподавателями зарубежных ученых (экспертов, специалистов) для проведения занятий в университете или привлечение иностранных студентов в университет и укрепление международных связей с университетом',
                            'en' => 'Contribution of professors and teachers to conducting classes in foreign (QS, THE, ARWU TOP-1000) universities, as well as the involvement of foreign scientists (experts, specialists) by professors and teachers to conduct classes at the university, or the involvement of foreign students in the university, and the strengthening of international relations with the university',
                        ],
                        'desc' => [
                            'uz' => 'QS, THE va ARWU kabi xalqaro tashkilotlari reyting ro‘yxatining nufuzli 1000 taligiga kiruvchi ta’lim muassasalari bilan davlatlararo va oliy ta’lim muassasalari o‘rtasidagi tuzilgan shartnomalar, kelishuvlar, xorijiy oliy ta’lim muassasasidan yuborilgan chaqiruv xatlari hamda OTMning tegishli buyrug‘i asosida baholanadi. (Top-100 bo‘lsa -3 ball, Top-300 bo‘lsa -2.5, Top-500 bo‘lsa -2 ball, Top-1000 bo‘lsa 1,5 ball, xorijlik talabalarni jalb qilgan bo‘lsa-3 ball)',
                            'kaa' => 'QS, THE hám ARWU sıyaqlı xalıqaralıq shólkemler reyting diziminiń abıraylı 1000 lıǵına kiriwshi bilimlendiriw mákemeleri menen mámleketler aralıq hám joqarı bilimlendiriw mákemeleri arasında dúzilgen shártnamalar, kelisimler, sırt el joqarı bilimlendiriw mákemesinen jiberilgen shaqırıw xatları hám de JOOnıń tiyisli buyrıǵı tiykarında bahalanadı. (Top-100 bolsa -3 ball, Top-300 bolsa -2.5, Top-500 bolsa -2 ball, Top-1000 bolsa 1,5 ball, sırt elli studentlerdi tartqan bolsa-3 ball)',
                            'ru' => 'Оценка проводится на основе договоров, соглашений, заключенных между образовательными учреждениями, входящими в топ-1000 рейтинга международных организаций, таких как QS, THE и ARWU, и межгосударственными и высшими образовательными учреждениями, пригласительных писем, направленных из зарубежного высшего образовательного учреждения, а также соответствующего приказа вуза. (Топ-100 - 3 балла, Топ-300 - 2,5 балла, Топ-500 - 2 балла, Топ-1000 - 1,5 балла, привлечение иностранных студентов - 3 балла)',
                            'en' => 'Educational institutions included in the top 1000 of the rating list of international organizations such as QS, THE and ARWU are evaluated on the basis of contracts, agreements concluded between interstate and higher educational institutions, letters of invitation sent from a foreign higher educational institution, as well as the relevant order of the university. (Top-100 - 3 points, Top-300 - 2.5 points, Top-500 - 2 points, Top-1000 - 1.5 points, 3 points for attracting foreign students)',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 3,
                            'no_degrees' => 3,
                            'foreign_lang' => 4,
                            'physical' => 4,
                        ],
                        'year' => 2025,
                        'formula_id' => 2,
                        'ai_prompt' => "You are an AI evaluator. Review the provided contracts or invitation letters. Check if the professor taught at a Top-1000 foreign university, invited foreign experts, or attracted foreign students. Point logic: Top-100 = 3, Top-300 = 2.5, Top-500 = 2, Top-1000 = 1.5. Attracting foreign students = 3. Return a JSON object strictly in this format: {\"status\": true/false, \"score\": max_applicable_points, \"reason\": \"explanation\"}.",
                    ],
                ],
            ],
            [
                'main' => [
                    'name' => [
                        'uz' => 'Ilmiy-innovatsion faoliyat',
                        'kaa' => 'Ilimiy-innovaciyalıq jumıs',
                        'ru' => 'Научно-инновационная деятельность',
                        'en' => 'Scientific and innovative activity',
                    ],
                    'report_id' => 1, 'upload' => '1', 'status' => '1',
                ],
                'children' => [
                    [
                        'name' => [
                            'uz' => 'OAK ro‘yxatiga kiritilgan xorijiy va mahalliy  ilmiy jurnallarda («Web of Science», «Scopus»dan tashqari) chop etilgan ilmiy maqolalar',
                            'kaa' => 'JAK dizimine kirgizilgen sırt el hám jergilikli ilimiy jurnallarda ("Web of Science," "Scopus"dan tısqarı) basıp shıǵarılǵan ilimiy maqalalar',
                            'ru' => 'Научные статьи, опубликованные в зарубежных и отечественных научных журналах, включенных в перечень ВАК (кроме "Web of Science," "Scopus")',
                            'en' => 'Scientific articles published in foreign and domestic scientific journals included in the HAC list (except for "Web of Science" and "Scopus")',
                        ],
                        'desc' => [
                            'uz' => 'Oliy attestatsiya komissiyasi ro‘yxatiga kiritilgan Xorijiy ilmiy jurnallarda («Web of Science», «Scopus»dan tashqari) chop etilgan ilmiy maqolalarga muvofiq baholanadi (xorijiy hamkorlikda chiqarilgan maqolalardan tashqari maqolalalar mualliflariga ball teng taqsimlanadi)',
                            'kaa' => 'Joqarı attestaciya komissiyası dizimine kirgizilgen Sırt el ilimiy jurnallarında ("Web of Science," "Scopus"dan tısqarı) basıp shıǵarılǵan ilimiy maqalalarǵa muwapıq bahalanadı (sırt elli birge islesiwde shıǵarılǵan maqalalardan tısqarı maqalalar avtorlarına ball teń bólistiriledi).',
                            'ru' => 'Оценивается в соответствии с научными статьями, опубликованными в зарубежных научных журналах (кроме "Web of Science," "Scopus"), включенных в список Высшей аттестационной комиссии (авторам статей, кроме статей, опубликованных в зарубежном сотрудничестве, баллы распределяются поровну).',
                            'en' => 'It is evaluated in accordance with scientific articles published in foreign scientific journals (except for "Web of Science" and "Scopus") included in the list of the Higher Attestation Commission (scores are distributed equally among the authors of articles, except for articles published in foreign cooperation).',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 2,
                            'no_degrees' => 3,
                            'foreign_lang' => 3,
                            'physical' => 3,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => "You are an AI evaluator. Analyze the article details. Verify it is published in a journal recognized by the HAC (OAK) and is NOT in Scopus/Web of Science. Extract the number of co-authors to distribute points equally. Return a JSON object strictly in this format: {\"status\": true/false, \"author_count\": number, \"reason\": \"explanation\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => 'Impakt-faktor jamlanmasiga kiruvchi jurnallarda chop etilgan maqolalar («Web of Science», «Scopus»dan tashqari) chop etilgan ilmiy maqolalar',
                            'kaa' => 'Impakt-faktor toplamına kiriwshi jurnallarda basıp shıǵarılǵan maqalalar ("Web of Science," "Scopus"dan tısqarı) basıp shıǵarılǵan ilimiy maqalalar',
                            'ru' => 'Статьи, опубликованные в журналах, входящих в совокупность импакт-факторов (кроме "Web of Science," "Scopus") научные статьи, опубликованные',
                            'en' => 'Articles published in journals included in the impact factor collection (except for "Web of Science" and "Scopus") published scientific articles',
                        ],
                        'desc' => [
                            'uz' => 'Impakt-faktor toplamına kiriwshi jurnallarda basıp shıǵarılǵan maqalalarda ("Web of Science," "Scopus"dan tısqarı) basıp shıǵarılǵan ilimiy maqalalarǵa muwapıq bahalanadı (shet elli birge islesiwde shıǵarılǵan maqalalardan tısqarı maqalalar avtorlarına ball teń bólistiriledi).',
                            'kaa' => 'Impakt-faktor toplamına kiriwshi jurnallarda basıp shıǵarılǵan maqalalarda ("Web of Science," "Scopus"dan tısqarı) basıp shıǵarılǵan ilimiy maqalalarǵa muwapıq bahalanadı (shet elli birge islesiwde shıǵarılǵan maqalalardan tısqarı maqalalar avtorlarına ball teń bólistiriledi).',
                            'ru' => 'Оценивается в соответствии с научными статьями, опубликованными в журналах, входящих в совокупность импакт-факторов (кроме "Web of Science," "Scopus") (за исключением статей, опубликованных в зарубежном сотрудничестве, баллы распределяются поровну между авторами статей).',
                            'en' => 'It is evaluated in accordance with scientific articles published in journals included in the impact factor collection (except for "Web of Science" and "Scopus") (scores are distributed equally among the authors of articles, with the exception of articles published in foreign cooperation).',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 2,
                            'no_degrees' => 3,
                            'foreign_lang' => 3,
                            'physical' => 3,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => "You are an AI evaluator. Verify the article is published in an Impact Factor journal (excluding Scopus/Web of Science). Extract the number of co-authors for point distribution. Return a JSON object strictly in this format: {\"status\": true/false, \"author_count\": number, \"reason\": \"explanation\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => '“SCOPUS” xalqaro ilmiy-texnik ma’lumotlar bazalaridagi Q1-Q4 kvartildagi jurnallarda nashr etilgan maqolalar',
                            'kaa' => '"SCOPUS" xalıqaralıq ilimiy-texnikalıq maǵlıwmatlar bazalarındaǵı Q1-Q4 kvartilindegi jurnallarda járiyalanǵan maqalalar',
                            'ru' => 'Статьи, опубликованные в журналах квартилей Q1-Q4 международных научно-технических баз данных "SCOPUS"',
                            'en' => 'Articles published in Q1-Q4 quartile journals in the international scientific and technical databases "SCOPUS"',
                        ],
                        'desc' => [
                            'uz' => 'Scopus va Web of Science bazasi orqali baholanadi (xorijiy hamkorlikda chiqarilgan maqolalardan tashqarilari mualliflariga ball teng taqsimlanadi). Q1, Q2-bo‘lsa -100%, Q3-Q4% bo‘lsa- 80%, konferensiyalarda nashr etilgan maqolalar -50%',
                            'kaa' => 'Scopus hám Web of Science bazası arqalı bahalanadı (shet elli birge islesiwde shıǵarılǵan maqalalardan tısqarı avtorlarına ball teń bólistiriledi). Q1, Q2 bolsa - 100%, Q3-Q4% bolsa - 80%, konferenciyalarda járiyalanǵan maqalalar - 50%.',
                            'ru' => 'Оценивается через базы данных Scopus и Web of Science (за исключением статей, опубликованных в зарубежном сотрудничестве, баллы распределяются поровну между авторами). Q1, Q2 - 100%, Q3-Q4% - 80%, статьи, опубликованные на конференциях - 50%',
                            'en' => 'It is evaluated through the Scopus and Web of Science databases (except for articles published in foreign cooperation, the authors are awarded equal points). Q1, Q2 - 100%, Q3-Q4% - 80%, articles published at conferences - 50%',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 5,
                            'no_degrees' => 5,
                            'foreign_lang' => 5,
                            'physical' => 5,
                        ],
                        'year' => 2025,
                        'formula_id' => 3,
                        'ai_prompt' => "You are an AI evaluator. Analyze the publication. Identify its quartile in Scopus/Web of Science: Q1/Q2 (100% weight), Q3/Q4 (80% weight), or Conference proceeding (50% weight). Extract the total number of co-authors. Return a JSON object strictly in this format: {\"status\": true/false, \"weight\": percentage_as_decimal, \"author_count\": number, \"reason\": \"explanation\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => '«Scopus», «Web of Science»,  «Research Gate» xalqaro ilmiy-texnik bazalaridagi xirsh indeksi',
                            'kaa' => '"Scopus," "Web of Science," "Research Gate" xalıqaralıq ilimiy-texnikalıq bazalarındaǵı xirsh indeksi',
                            'ru' => 'Индекс хирша в международных научно-технических базах "Scopus," "Web of Science," "Research Gate"',
                            'en' => 'Hirsch index in international scientific and technical databases "Scopus," "Web of Science," "Research Gate"',
                        ],
                        'desc' => [
                            'uz' => '«Scopus» h≥5 bo‘lsa 100%, h=4 bo‘lsa 75%, h=3 bo‘lsa 50%, h≤2 bo‘lsa 25%<br>«Web of Science» h≥5 bo‘lsa 100%, h=4 bo‘lsa 75%, h=3 bo‘lsa 50%, h≤2 bo‘lsa 25%<br>«Research Gate» h≥5 bo‘lsa 100%, h=4 bo‘lsa 75%, h=3 bo‘lsa 50%, h≤2 bo‘lsa 25%',
                            'kaa' => '"Scopus" h≥5 bolsa 100%, h=4 bolsa 75%, h=3 bolsa 50%, h≤2 bolsa 25%<br>"Web of Science" h≥5 bolsa 100%, h=4 bolsa 75%, h=3 bolsa 50%, h≤2 bolsa 25%<br>"Research Gate" h≥5 bolsa 100%, h=4 bolsa 75%, h=3 bolsa 50%, h≤2 bolsa 25%',
                            'ru' => '"Scopus" 100% при h≥5, 75% при h=4, 50% при h=3, 25% при h≤2<br>"Web of Science" 100% при h≥5, 75% при h=4, 50% при h=3, 25% при h≤2<br>"Research Gate" 100% при h≥5, 75% при h=4, 50% при h=3, 25% при h≤2',
                            'en' => '"Scopus" 100% if h≥5, 75% if h=4, 50% if h=3, 25% if h≤2<br>"Web of Science" 100% if h≥5, 75% if h=4, 50% if h=3, 25% if h≤2<br>"Research Gate" 100% if h≥5, 75% if h=4, 50% if h=3, 25% if h≤2',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 3,
                            'no_degrees' => 2,
                            'foreign_lang' => 2,
                            'physical' => 2,
                        ],
                        'year' => 2025,
                        'formula_id' => 2,
                        'ai_prompt' => "You are an AI evaluator. Extract the author's h-index from the provided Scopus, Web of Science, or ResearchGate evidence. Calculate weight: h>=5 (1.0), h=4 (0.75), h=3 (0.50), h<=2 (0.25). Return a JSON object strictly in this format: {\"status\": true, \"weight\": calculated_weight, \"h_index\": number, \"reason\": \"explanation\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => 'Monografiya yozganligi yoki lug‘at tuzganligi',
                            'kaa' => 'Monografiya jazǵanlıǵı yamasa sózlik dúzgenligi',
                            'ru' => 'Написание монографии или составление словаря',
                            'en' => 'Whether he wrote a monograph or compiled a dictionary',
                        ],
                        'desc' => [
                            'uz' => 'Belgilangan talab va tartibda tayyorlanib, universitet kengash qarori bilan ruxsat etilib, chop qilinganligi hamda ISBN  raqami orqali aniqlanadi.',
                            'kaa' => 'Belgilengen talap hám tártipte tayarlanıp, universitet keńesi qararı menen ruqsat etilip, basıp shıǵarılǵanlıǵı hám de ISBN nomeri arqalı anıqlanadı.',
                            'ru' => 'Подготовлено в соответствии с установленными требованиями и порядком, разрешено решением совета университета, опубликовано и определяется по номеру ISBN.',
                            'en' => 'Prepared in accordance with the established requirements and procedure, approved by a decision of the university council, published, and determined by ISBN number.',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 2,
                            'no_degrees' => 3,
                            'foreign_lang' => 3,
                            'physical' => 3,
                        ],
                        'year' => 2025,
                        'formula_id' => 2,
                        'ai_prompt' => "You are an AI evaluator. Check the evidence for a published monograph or dictionary. Verify the presence of an ISBN number and a university council approval decision. Return a JSON object strictly in this format: {\"status\": true/false, \"reason\": \"explanation\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => 'Ilmiy maslahatchiligida fan doktori (DSC) ilmiy darajali kadr tayyorlagani uchun',
                            'kaa' => 'Ilimiy másláhátshi retinde ilim doktorı (DSC) ilimiy dárejeli kadr tayarlaǵanı ushın',
                            'ru' => 'За подготовку в качестве научного консультанта кадров с ученой степенью доктора наук (DSC)',
                            'en' => 'For training personnel with a Doctor of Science (DSC) degree under the supervision of a scientific consultant',
                        ],
                        'desc' => [
                            'uz' => 'OAK tomonidan taqdim etilgan tegishli hujjat (diplom) asosida baholanadi.',
                            'kaa' => 'JAK tárepinen usınılǵan tiyisli hújjet (diplom) tiykarında bahalanadı.',
                            'ru' => 'Оценивается на основании соответствующего документа (диплома), представленного ВАК.',
                            'en' => 'The assessment is carried out on the basis of a corresponding document (diploma) submitted by the HAC.',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 3,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => "You are an AI evaluator. Verify the provided diploma or HAC (OAK) document proves the professor successfully supervised a Doctor of Science (DSc) candidate. Return a JSON object strictly in this format: {\"status\": true/false, \"reason\": \"explanation\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => 'Ilmiy rahbarligida falsafa doktori (PhD) ilmiy darajali kadr tayyorlagani uchun',
                            'kaa' => 'Ilimiy basshılıǵında filosofiya doktorı (PhD) ilimiy dárejeli kadr tayarlaǵanı ushın',
                            'ru' => 'За подготовку под научным руководством кадров с ученой степенью доктора философии (PhD)',
                            'en' => 'For training personnel with a Doctor of Philosophy (PhD) degree under scientific supervision',
                        ],
                        'desc' => [
                            'uz' => 'OAK tomonidan taqdim etilgan tegishli hujjat (diplom) asosida baholanadi.',
                            'kaa' => 'JAK tárepinen usınılǵan tiyisli hújjet (diplom) tiykarında bahalanadı.',
                            'ru' => 'Оценивается на основании соответствующего документа (диплома), представленного ВАК.',
                            'en' => 'The assessment is carried out on the basis of a corresponding document (diploma) submitted by the HAC.',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 3,
                            'foreign_lang' => 3,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => "You are an AI evaluator. Verify the provided diploma or HAC (OAK) document proves the professor successfully supervised a Doctor of Philosophy (PhD) candidate. Return a JSON object strictly in this format: {\"status\": true/false, \"reason\": \"explanation\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => 'Ilmiy-tadqiqot ishlarining samaradorligi: PATENT',
                            'kaa' => 'Ilimiy-izertlew jumıslarınıń nátiyjeliligi: PATENT',
                            'ru' => 'Эффективность научно-исследовательских работ: ПАТЕНТ',
                            'en' => 'Effectiveness of research work: PATENT',
                        ],
                        'desc' => [
                            'uz' => 'Ixtiro, foydali model, sanoat namunalari va seleksiya yutuqlari uchun olingan patentlar asosida aniqlanadi. Huquq egasi universitet yoki universitet o‘qituvchisi bo‘lishi kerak. Huquq egasi (lari) o‘rtasida teng taqsimlanadi.',
                            'kaa' => 'Oylap tabıw, paydalı model, sanaat úlgileri hám selekciya jetiskenlikleri ushın alınǵan patentler tiykarında anıqlanadı. Huqıq iesi universitet yamasa universitet oqıtıwshısı bolıwı kerek. Huqiq iyesi (leri) arasında teń bólistiriledi.',
                            'ru' => 'На основании полученных патентов на изобретения, полезные модели, промышленные образцы и селекционные достижения. Правообладателем должен быть университет или преподаватель университета. Распределяется поровну между правообладателем (правообладателями).',
                            'en' => 'On the basis of patents for inventions, utility models, industrial designs, and selection achievements. The rights holder must be a university or university lecturer. Shared equally among the rights holder (s).',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 3,
                            'no_degrees' => 4,
                            'foreign_lang' => 4,
                            'physical' => 4,
                        ],
                        'year' => 2025,
                        'formula_id' => 3,
                        'ai_prompt' => "You are an AI evaluator. Review the patent document (invention, utility model, etc.). Ensure the university or professor is listed as the rights holder. Extract the total number of rights holders to distribute points. Return a JSON object strictly in this format: {\"status\": true/false, \"rights_holders_count\": number, \"reason\": \"explanation\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => 'Ilmiy-tadqiqot ishlarining samaradorligi: MUALLIFLIK GUVOHNOMALARI',
                            'kaa' => 'Ilimiy-izertlew jumıslarınıń nátiyjeliligi: AVTORLÍQ GÚWÁLÍQLARÍ',
                            'ru' => 'Эффективность научно-исследовательских работ: АВТОРСКИЕ УДОСТОВЕРЕНИЯ',
                            'en' => 'Effectiveness of research work: AUTHOR’S CERTIFICATES',
                        ],
                        'desc' => [
                            'uz' => 'Axborot kommunikatsiya texnologiyalariga oid dasturlar va elektron ma’lumotlar bazalari uchun olingan guvohnomalar, mualliflik huquqi bilan himoyalangan turli materiallar orqali aniqlanadi.',
                            'kaa' => 'Málimleme kommunikaciya texnologiyalarına tiyisli baǵdarlamalar hám elektron maǵlıwmatlar bazaları ushın alınǵan gúwalıqlar, avtorlıq huqıq penen qorǵalǵan túrli materiallar arqalı anıqlanadı.',
                            'ru' => 'Информационно-коммуникационные технологии определяются по программам и электронным базам данных, полученным свидетельствам, различным материалам, защищенным авторским правом.',
                            'en' => 'It is determined through certificates obtained for information and communication technology programs and electronic databases, as well as various materials protected by copyright.',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 1,
                            'no_degrees' => 2,
                            'foreign_lang' => 2,
                            'physical' => 2,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => "You are an AI evaluator. Verify the submitted certificate is for a software program or electronic database (DGU or copyright certificate). Return a JSON object strictly in this format: {\"status\": true/false, \"reason\": \"explanation\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => 'Universitet nomidan ilmiy tadbirlardagi ishtirok',
                            'kaa' => 'Universitet atınan ilimiy ilajlarda qatnasıw',
                            'ru' => 'Участие в научных мероприятиях от имени Университета',
                            'en' => 'Participation in scientific events on behalf of the University',
                        ],
                        'desc' => [
                            'uz' => 'Ma’ruza, ko‘rgazma, yarmarka, seminar, tanlovlar yoki konferensiyalarda ma’ruza bilan qatnashishi yoki ushbu ilmiy tadbirlarda sovrinli o‘rinlar uchun',
                            'kaa' => 'Bayanat, kórgizbe, yarmarka, seminar, tańlawlar yamasa konferenciyalarda bayanat penen qatnasıwı yamasa usı ilimiy ilajlarda sıylı orınlar ushın',
                            'ru' => 'За участие с докладом на лекциях, выставках, ярмарках, семинарах, конкурсах или конференциях или за призовые места на этих научных мероприятиях',
                            'en' => 'Participation in lectures, exhibitions, fairs, seminars, competitions, or conferences, or for prize-winning places in these scientific events',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 2,
                            'no_degrees' => 4,
                            'foreign_lang' => 2,
                            'physical' => 2,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => "You are an AI evaluator. Review the evidence (certificate, program). Confirm the professor participated with a lecture/presentation at an exhibition, seminar, or conference, or won a prize, representing the university. Return a JSON object strictly in this format: {\"status\": true/false, \"reason\": \"explanation\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => 'Bevosita rahbarligida respublika miqyosdagi yoki xalqaro olimpiadalarida, nufuzli tanlovlarda, (sovrinli o‘rinlarni qo‘lga kiritgan, mukofot (diplom)-larga (stipendiat) sazovor bo‘lgan talabalari uchun',
                            'kaa' => 'Tikkeley basshılıǵında respublikalıq kólemdegi yamasa xalıqaralıq olimpiadalarda, abıraylı tańlawlarda, sıylı orınlardı qolǵa kirgizgen, sıylıq (diplom) larǵa (stipendiat) ie bolǵan studentleri ushın',
                            'ru' => 'Для студентов, занявших призовые места, удостоенных премий (дипломов) (стипендиатов) на республиканских или международных олимпиадах, престижных конкурсах под непосредственным руководством',
                            'en' => 'For students who have won prizes, awards (diplomas), or scholarships at national or international Olympiads and prestigious competitions under their direct supervision',
                        ],
                        'desc' => [
                            'uz' => 'Talabalarga rahbarligi to‘g‘risidagi buyruq yoki kengash qarori, talaba diplomi, sertifikati va boshqa hujjatlari orqali aniqlanadi.',
                            'kaa' => 'Studentlerge basshılıǵı haqqındaǵı buyrıq yamasa keńes qararı, student diplomı, sertifikatı hám basqa hújjetleri arqalı anıqlanadı.',
                            'ru' => 'Определяется приказом или решением совета о руководстве студентами, дипломом, сертификатом и другими документами студента.',
                            'en' => 'It is determined by order or decision of the student council, diploma, certificate and other documents of the student.',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 3,
                            'no_degrees' => 4,
                            'foreign_lang' => 4,
                            'physical' => 4,
                        ],
                        'year' => 2025,
                        'formula_id' => 2,
                        'ai_prompt' => "You are an AI evaluator. Check the student's diploma or certificate. Verify the student won a prize in a national/international competition or Olympiad, and confirm the professor was their direct supervisor (via official order). Return a JSON object strictly in this format: {\"status\": true/false, \"reason\": \"explanation\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => 'Talabalarning to‘garaklariga rahbarlik qilish',
                            'kaa' => 'Studentlerdiń dógereklerine basshılıq etiw',
                            'ru' => 'Руководство студенческими кружками',
                            'en' => 'Leadership of student clubs',
                        ],
                        'desc' => [
                            'uz' => 'To‘garak buyrug‘i va rejasi',
                            'kaa' => 'Dógerek buyrıǵı hám rejesi',
                            'ru' => 'Приказ и план кружка',
                            'en' => 'Order and plan of the circle',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 3,
                            'no_degrees' => 3,
                            'foreign_lang' => 3,
                            'physical' => 3,
                        ],
                        'year' => 2025,
                        'formula_id' => 2,
                        'ai_prompt' => "You are an AI evaluator. Check the evidence for the professor's leadership of a student club. Look for an official order (buyruq) and a club plan (reja). Return a JSON object strictly in this format: {\"status\": true/false, \"reason\": \"explanation\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => 'Sohalar buyurtmalari asosida (xo‘jalik, innovatsion shartnomalari orqali) o‘tkazilgan ilmiy (ilmiy-ijodiy) tadqiqotlari orqali topilgan mablag‘',
                            'kaa' => 'Tarawlardıń buyırtpaları tiykarında (xojalıq, innovaciya shártnamaları arqalı) ótkerilgen ilimiy (ilimiy-dóretiwshilik) izertlewleri arqalı tabılǵan qarjı',
                            'ru' => 'Средства, полученные за счет научных (научно-творческих) исследований, проведенных на основе отраслевых заказов (хозяйственных, инновационных договоров)',
                            'en' => 'Funds earned through scientific (scientific-creative) research conducted on the basis of industry orders (through economic, innovative contracts)',
                        ],
                        'desc' => [
                            'uz' => 'Sohalar buyurtmalari asosida (xo‘jalik, innovatsion shartnomalari orqali) o‘tkazilgan ilmiy (ilmiy-ijodiy) tadqiqotlariga rahbarlik yoki ishtiroki va ishlab topilgan mablag‘lr asosida baholanadi. Mablag‘ universitet hisobiga tushgan bo‘lishi kerak.',
                            'kaa' => 'Tarawlardıń buyırtpaları tiykarında (xojalıq, innovaciyalıq shártnamaları arqalı) ótkerilgen ilimiy (ilimiy-dóretiwshilik) izertlewlerine basshılıq yamasa qatnasıwı hám islep tabılǵan qarjılar tiykarında bahalanadı. Qarjı universitet esabına túsken bolıwı kerek.',
                            'ru' => 'Оценивается на основе руководства или участия в научных (научно-творческих) исследованиях, проводимых по заказам отраслей (через хозяйственные, инновационные договоры), и заработанных средств. Деньги должны были поступить на счет университета.',
                            'en' => 'It is evaluated based on leadership or participation in scientific (scientific-creative) research conducted on the basis of industry orders (through economic, innovative contracts) and earned funds. The funds must have been deposited into the university’s account.',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 5,
                            'no_degrees' => 4,
                            'foreign_lang' => 4,
                            'physical' => 4,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => "You are an AI evaluator. Review the economic or innovative contract documents/bank statements. Verify that funds were successfully transferred to the university's account through the professor's research or leadership. Return a JSON object strictly in this format: {\"status\": true/false, \"reason\": \"explanation\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => 'Davlat grantlari asosida ilmiy-tadqiqot loyihalarda ishtiroki',
                            'kaa' => 'Mámleketlik grantlar tiykarında ilimiy-izertlew joybarlarında qatnasıwı.',
                            'ru' => 'Участие в научно-исследовательских проектах на основе государственных грантов',
                            'en' => 'Participation in research projects based on state grants',
                        ],
                        'desc' => [
                            'uz' => 'Davlat grantlari asosida o‘tkazilgan tadqiqotlariga rahbarligi yoki a’zoligi hujjatlar asosida baholanadi. Loyiha universitet doirasida bo‘lishi lozim.  Boshqa OTMlardagi ishtiroki hisobga olinmaydi.',
                            'kaa' => 'Mámleketlik grantlar tiykarında ótkerilgen izertlewlerine basshılıǵı yamasa aǵzalıǵı hújjetler tiykarında bahalanadı. Joybar universitet sheńberinde bolıwı kerek.  Basqa JOOlardaǵı qatnasıwı esapqa alınbaydı.',
                            'ru' => 'Руководство или членство в исследованиях, проводимых на основе государственных грантов, оценивается на основании документов. Проект должен быть в рамках университета.  Участие в других вузах не учитывается.',
                            'en' => 'Leadership or membership in research conducted on the basis of state grants is evaluated on the basis of documents. The project should be within the university.  Participation in other universities is not taken into account.',
                        ],
                        'observation' => 'project_finished',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 4,
                            'no_degrees' => 1,
                            'foreign_lang' => 1,
                            'physical' => 1,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => "You are an AI evaluator. Verify the professor's leadership or membership in a state grant research project. Confirm the project is affiliated with the university. Return a JSON object strictly in this format: {\"status\": true/false, \"reason\": \"explanation\"}.",
                    ],
                    [
                        'name' => [
                            'uz' => 'Ixtisoslashgan ilmiy kengashlarda rais, kotib va a’zo, shuningdek, respublika ilmiy-texnik kengashlarda a’zolik uchun',
                            'kaa' => 'Qánigelestirilgen ilimiy keńeslerde baslıq, xatker hám aǵza, sonday-aq, respublikalıq ilimiy-texnikalıq keńeslerde aǵzalıq ushın',
                            'ru' => 'За председателя, секретаря и члена специализированных научных советов, а также за членство в республиканских научно-технических советах',
                            'en' => 'Chairman, Secretary, and member of specialized scientific councils, as well as for membership in republican scientific and technical councils',
                        ],
                        'desc' => [
                            'uz' => 'OAK rayosati va vazirlik qarori, buyrug‘i asosida aniqlanadi.',
                            'kaa' => 'JAK prezidiumi hám ministrlik qararı, buyrıǵı tiykarında aniqlanadi.',
                            'ru' => 'Определяется на основании решения, приказа президиума ВАК и министерства.',
                            'en' => 'Determined on the basis of a decision or order of the HAC Presidium and the Ministry.',
                        ],
                        'observation' => 'end_of_council',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 2,
                            'foreign_lang' => 2,
                        ],
                        'year' => 2025,
                        'formula_id' => 2,
                        'ai_prompt' => "You are an AI evaluator. Review the provided HAC (OAK) or Ministry decree. Confirm the professor serves as a chairman, secretary, or member of a specialized scientific council or national technical council. Return a JSON object strictly in this format: {\"status\": true/false, \"reason\": \"explanation\"}.",
                    ],
                ],
            ],
            [
                'main' => [
                    'name' => [
                        'uz' => 'Ijtimoiy-ma’naviy faoliyati, ijro va mehnat intizomi',
                        'kaa' => 'Sociallıq-ruwxıy iskerligi, atqarıw hám miynet tártibi',
                        'ru' => 'Социально-духовная деятельность, исполнительская и трудовая дисциплина',
                        'en' => 'Socio-spiritual activity, performance, and labor discipline',
                    ],
                    'report_id' => 1, 'upload' => '1', 'status' => '1',
                ],
                'children' => [
                    [
                        'name' => [
                            'uz' => 'OAV yoki ijtimoiy tarmoqlarda universitet va mamlakatda amalga oshirilayotgan islohotlar yuzasidan chiqishlar qilganlig',
                            'kaa' => 'ǴXQ yamasa sociallıq tarmaqlarda universitet hám mámlekette ámelge asırılıp atırǵan reformalar boyınsha shıǵıp sóylegenligi',
                            'ru' => 'Выступления в СМИ или социальных сетях по поводу реформ, проводимых в университете и стране',
                            'en' => 'Making appearances in the media or social networks regarding the university and the reforms being implemented in the country',
                        ],
                        'desc' => [
                            'uz' => 'Bajarilgan ishlar bo‘yicha taqdim etilgan hujjatlar, videolavhalar asosida aniqlanadi va baholanadi (respublika, xorijiy OAVlarda).',
                            'kaa' => 'Orınlanǵan jumıslar boyınsha usınılǵan hújjetler, video kórinisler tiykarında anıqlanadı hám bahalanadı (respublika, sırt el ǵalaba xabar qurallarında).',
                            'ru' => 'Определяется и оценивается на основе представленных документов, видеороликов о проделанной работе (в республиканских, зарубежных СМИ).',
                            'en' => 'The results of the work performed are determined and evaluated based on submitted documents and video materials (in national and foreign media).',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 3,
                            'no_degrees' => 3,
                            'foreign_lang' => 2,
                            'physical' => 3,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => null,
                    ],
                    [
                        'name' => [
                            'uz' => 'Davlat hokimiyati va boshqaruvi organlarining murojaatiga asosan ilmiy-amaliy takliflarni tayyor-lash va ishtirok etish',
                            'kaa' => 'Mámleketlik hákimiyat hám basqarıw uyımlarınıń múrájatına tiykarlanıp ilimiy-ámeliy usınıslardı tayarlaw hám qatnasıw',
                            'ru' => 'Подготовка и участие в научно-практических предложениях на основе обращений органов государственной власти и управления',
                            'en' => 'Preparation and participation in scientific and practical proposals based on appeals from state authorities and administration bodies',
                        ],
                        'desc' => [
                            'uz' => 'Davlat hokimiyati va boshqaruvi organlarining murojaati asos qilinadi',
                            'kaa' => 'Mámleketlik hákimiyat hám basqarıw uyımlarınıń múrájatı tiykarlanadı.',
                            'ru' => 'Основанием является обращение органов государственной власти и управления.',
                            'en' => 'The basis is the appeal of state authorities and administration bodies.',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 1,
                            'no_degrees' => 1,
                            'foreign_lang' => 1,
                            'physical' => 2,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => null,
                    ],
                    [
                        'name' => [
                            'uz' => 'Bevosita o‘zining tashabbusi bilan ma’naviy-ma’rifiy, adabiy uchrashuvlar, intel-lektual o‘yinlar, mushoira kechalari, turli tanlovlar tashkil etganligi',
                            'kaa' => 'Tikkeley óziniń baslaması menen ruwxıy-aǵartıwshılıq, ádebiy ushırasıwlar, intellektual oyınlar, mushayra kesheleri, túrli tańlawlar shólkemlestirgenligi.',
                            'ru' => 'Организация по собственной инициативе духовно-просветительских, литературных встреч, интеллектуальных игр, вечеров поэзии, различных конкурсов;',
                            'en' => 'Organizing spiritual-educational and literary meetings, intellectual games, poetry evenings, and various competitions on his own initiative;',
                        ],
                        'desc' => [
                            'uz' => 'Ma’naviy-ma’rifiy, adabiy uchrashuvlar (bayonlari), intellektual o‘yinlar, mushoira kechalari, turli tanlovlar tashkil (e’lon) etganligi',
                            'kaa' => 'Ruwxıy-aǵartıwshılıq, ádebiy ushırasıwlar (bayanatları), intellektual oyınlar, mushayra kesheleri, túrli tańlawlar shólkemlestirilgenligi (járiyalanǵanlıǵı)',
                            'ru' => 'Организация (объявление) духовно-просветительских, литературных встреч, интеллектуальных игр, поэтических вечеров, различных конкурсов',
                            'en' => 'Organization (announcement) of spiritual, educational, and literary meetings (expressions), intellectual games, poetry evenings, and various competitions',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 2,
                            'no_degrees' => 3,
                            'foreign_lang' => 1,
                            'physical' => 3,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => null,
                    ],
                    [
                        'name' => [
                            'uz' => 'Talabalar bilan tarbiyaviy ish bo‘yicha tadbirlarda ishtirok etish',
                            'kaa' => 'Studentler menen tárbiyalıq jumıs boyınsha ilajlarda qatnasıw',
                            'ru' => 'Участие в мероприятиях по воспитательной работе со студентами',
                            'en' => 'Participation in educational work activities with students',
                        ],
                        'desc' => [
                            'uz' => 'Ma’naviy-ma’rifiy ishlar, sport klublari, madaniy tadbirlar va Universitetga biriktirilgan mahalalarda tadbirlar olib borish hamda boshqalar',
                            'kaa' => 'Ruwxıy-aǵartıwshılıq jumıslar, sport klubları, mádeniy ilajlar hám Universitetke biriktirilgen máhállelerde ilajlar ótkeriw hám basqalar',
                            'ru' => 'Проведение духовно-просветительской работы, спортивных клубов, культурных мероприятий и мероприятий в махаллях, закрепленных за Университетом, и др.',
                            'en' => 'Conducting spiritual and educational work, sports clubs, cultural events, and events in the mahallas assigned to the University, etc.',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 2,
                            'no_degrees' => 3,
                            'foreign_lang' => 2,
                            'physical' => 2,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => null,
                    ],
                    [
                        'name' => [
                            'uz' => 'Olingan davlat mukofotlari va respublika darajasidagi tashakkurnomalar',
                            'kaa' => 'Alınǵan mámleketlik sıylıqlar hám respublika dárejesindegi alǵısnamalar',
                            'ru' => 'Полученные государственные награды и благодарности республиканского уровня',
                            'en' => 'Received state awards and letters of appreciation at the national level',
                        ],
                        'desc' => [
                            'uz' => 'Guvohnoma yoki respublika darajasidagi tashakkurnomaning muhr bosilgan va imzolangan nusxasi',
                            'kaa' => 'Gúwalıq yamasa respublika dárejesindegi minnetdarshılıqtıń mór basılǵan hám qol qoyılǵan nusqası.',
                            'ru' => 'Копия удостоверения или благодарности республиканского уровня, заверенная печатью и подписью',
                            'en' => 'A stamped and signed copy of the certificate or national-level letter of appreciation',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 2,
                            'no_degrees' => 1,
                            'foreign_lang' => 2,
                            'physical' => 2,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => null,
                    ],
                    [
                        'name' => [
                            'uz' => 'Universitetning Ichki tartib qoidalari, odob-ahloq kodeksi hamda mehnat shartnomasida belgilangan vazifalarni o‘z vaqtida va sifatli bajarish holati',
                            'kaa' => 'Universitettiń Ishki tártip qaǵıydaları, ádep-ikramlılıq kodeksi hám de miynet shártnamasında belgilengen wazıypalardı óz waqtında hám sapalı orınlaw jaǵdayı',
                            'ru' => 'Состояние своевременного и качественного выполнения задач, определенных Правилами внутреннего распорядка, кодексом этики и трудовым договором Университета',
                            'en' => 'The state of timely and high-quality fulfillment of tasks defined in the University’s Internal Regulations, Code of Ethics, and employment contract',
                        ],
                        'desc' => [
                            'uz' => 'Intizomiy jazoga tortilmagan bo‘lsa',
                            'kaa' => 'Intizamıy jazaǵa tartılmaǵan bolsa',
                            'ru' => 'Не подвергались дисциплинарному взысканию',
                            'en' => 'Has not been subjected to disciplinary action',
                        ],
                        'observation' => 'current',
                        'report_id' => 1,
                        'checking' => 'ai',
                        'upload' => '1', 'status' => '1',
                        'evaluation' => [
                            'hold_degrees' => 2,
                            'no_degrees' => 3,
                            'foreign_lang' => 1,
                            'physical' => 2,
                        ],
                        'year' => 2025,
                        'formula_id' => 1,
                        'ai_prompt' => null,
                    ],
                ],
            ],
        ];

        foreach ($criteria as $criterion) {
            $c = Criterion::create([
                'name' => $criterion['main']['name'],
                'report_id' => $criterion['main']['report_id'],
                'upload' => $criterion['main']['upload'],
                'status' => $criterion['main']['status'],
            ]);
            foreach ($criterion['children'] as $child) {
                $ch = Criterion::create([
                    'name' => $child['name'],
                    'desc' => $child['desc'],
                    'observation' => $child['observation'],
                    'parent_id' => $c->id,
                    'ai_prompt' => $child['ai_prompt'],
                    'report_id' => $child['report_id'],
                    'checking' => $child['checking'],
                    'upload' => $child['upload'],
                    'status' => $child['status'],
                    'formula_id' => $child['formula_id'],
                ]);
                CriterionYear::create([
                    'criterion_id' => $ch->id,
                    'year_id' => $child['year'],
                ]);
                foreach ($child['evaluation'] as $key => $eva) {
                    CriterionEvaluation::create([
                        'criterion_id' => $ch->id,
                        'evaluation' => $key,
                        'score' => $eva
                    ]);
                }
            }
        }
    }
}
